/* libmenu-cache.vapi generated by vapigen, do not modify. */

namespace Menu {
	[CCode (cheader_filename = "libmenu-cache.h", ref_function = "menu_cache_ref", unref_function = "menu_cache_unref")]
	[Compact]
	public class Cache {
		public void* add_reload_notify (GLib.Func func);
		public uint32 get_desktop_env_flag (string desktop_env);
		public unowned Menu.CacheDir get_dir_from_path (string path);
		public unowned Menu.CacheDir get_root_dir ();
		public static void init (int flags);
		public unowned GLib.SList list_all_apps ();
		public static unowned Menu.Cache lookup (string menu_name);
		public static unowned Menu.Cache lookup_sync (string menu_name);
		public bool reload ();
		public void remove_reload_notify (void* notify_id);
	}
	[CCode (cheader_filename = "libmenu-cache.h")]
	[Compact]
	public class CacheApp {
		public unowned string get_exec ();
		public bool get_is_visible (uint32 de_flags);
		public uint32 get_show_flags ();
		public bool get_use_sn ();
		public bool get_use_terminal ();
		public unowned string get_working_dir ();
	}
	[CCode (cheader_filename = "libmenu-cache.h")]
	[Compact]
	public class CacheDir {
		public unowned GLib.SList get_children ();
		public unowned string make_path ();
	}
	[CCode (cheader_filename = "libmenu-cache.h", ref_function = "menu_cache_item_ref", unref_function = "menu_cache_item_unref")]
	[Compact]
	public class CacheItem {
		public unowned string get_comment ();
		public unowned string get_file_basename ();
		public unowned string get_file_dirname ();
		public unowned string get_file_path ();
		public unowned string get_icon ();
		public unowned string get_id ();
		public unowned string get_name ();
		public unowned Menu.CacheDir get_parent ();
	}
	[CCode (cheader_filename = "libmenu-cache.h", cprefix = "FLAG_USE_", has_type_id = false)]
	public enum CacheItemFlag {
		TERMINAL,
		SN
	}
	[CCode (cheader_filename = "libmenu-cache.h", cprefix = "", has_type_id = false)]
	public enum CacheShowFlag {
		SHOW_IN_LXDE,
		SHOW_IN_GNOME,
		SHOW_IN_KDE,
		SHOW_IN_XFCE,
		SHOW_IN_ROX,
		N_KNOWN_DESKTOPS
	}
	[CCode (cheader_filename = "libmenu-cache.h", cprefix = "MENU_CACHE_TYPE_", has_type_id = false)]
	public enum CacheType {
		NONE,
		DIR,
		APP,
		SEP
	}
}
